language: go
sudo: false

go:
  - 1.3.3
  - 1.4.3
  - 1.5.3
  - 1.6beta2

os:
  - linux
  - osx

notifications:
  irc:
    channels:
      - "chat.freenode.net#restic"
    on_success: change
    on_failure: change
    skip_join: true

install:
  - go version
  - export GOBIN="$GOPATH/bin"
  - export PATH="$PATH:$GOBIN"
  - export GOPATH="$GOPATH:${TRAVIS_BUILD_DIR}/Godeps/_workspace"
  - go env

script:
  - go run run_integration_tests.go

after_success:
  - goveralls -coverprofile=all.cov -service=travis-ci -repotoken "$COVERALLS_TOKEN" || true
