language: go
sudo: false

go:
  - 1.7.5
  - 1.8.1
  - tip

os:
  - linux
  - osx

env:
  matrix:
    RESTIC_TEST_FUSE=0

matrix:
  exclude:
    - os: osx
      go: 1.7.5
    - os: osx
      go: tip
    - os: linux
      go: 1.8.1
  include:
    - os: linux
      go: 1.8.1
      sudo: true
      env:
        RESTIC_TEST_FUSE=1
  allow_failures:
    - go: tip

branches:
  only:
    - master

notifications:
  irc:
    channels:
      - "chat.freenode.net#restic"
    on_success: change
    on_failure: change
    skip_join: true

install:
  - go version
  - export GOBIN="$GOPATH/bin"
  - export PATH="$PATH:$GOBIN"
  - go env

script:
  - travis_wait go run run_integration_tests.go

after_success:
  - bash <(curl -s https://codecov.io/bash) -f all.cov
