clone_folder: c:\restic

environment:
  GOPATH: c:\gopath

init:
  - ps: >-
      $app = Get-WmiObject -Class Win32_Product -Filter "Vendor = 'http://golang.org'"

      if ($app) {
        $app.Uninstall()
      }

install:
  - rmdir c:\go /s /q
  - appveyor DownloadFile https://storage.googleapis.com/golang/go1.7.windows-amd64.msi
  - msiexec /i go1.7.windows-amd64.msi /q
  - go version
  - go env
  - appveyor DownloadFile http://sourceforge.netcologne.de/project/gnuwin32/tar/1.13-1/tar-1.13-1-bin.zip -FileName tar.zip
  - 7z x tar.zip bin/tar.exe
  - set PATH=bin/;%PATH%

build_script:
  - go run run_integration_tests.go
