
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"


[[constraint]]
  branch = "master"
  name = "bazil.org/fuse"

[[constraint]]
  name = "github.com/elithrar/simple-scrypt"
  branch = "master"

[[constraint]]
  name = "github.com/minio/minio-go"
  version = "3.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/ncw/swift"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  name = "github.com/pkg/profile"
  version = "1.2.1"

[[constraint]]
  branch = "master"
  name = "github.com/pkg/sftp"

[[constraint]]
  name = "github.com/pkg/xattr"
  version = "0.2.1"

[[constraint]]
  name = "github.com/restic/chunker"
  version = "0.1.0"

[[constraint]]
  branch = "master"
  name = "github.com/spf13/cobra"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[[constraint]]
  branch = "master"
  name = "golang.org/x/sys"

[[constraint]]
  name = "github.com/kurin/blazer"
  branch = "master"
